site_name: 杭电计科英才学习指南
repo_name: HDU-CSHonor/CSHonor-Courses
repo_url: https://github.com/HDU-CSHonor/CSHonor-Courses
edit_uri: tree/master/docs
copyright: Copyright &copy; 2023 杭州电子科技大学计算机科学英才班

nav:
  - 主页: 
    - index.md
    - 贡献指南: contributing.md
    - 课程页面模板: template.md
  - 数理基础课:
    - math_phys/index.md
    - 数学分析1:    math_phys/math_analysis1/index.md
    - 数学分析2:    math_phys/math_analysis2/index.md
    - 高等代数1:    math_phys/advanced_algebra1/index.md
    - 高等代数2:    math_phys/advanced_algebra2/index.md
    - 概率论与数理统计: math_phys/probability/index.md
    - 大学物理1: math_phys/physics1/index.md
    - 大学物理2: math_phys/physics2/index.md


theme:
    name: material
    language: 'zh'
    favicon: images/icon.jpg